# Generated by Django 2.2.7 on 2019-11-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191123_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=255, unique=True, verbose_name='nickname'),
        ),
    ]
