# Generated by Django 3.0.2 on 2020-02-12 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Item ',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_end', models.BooleanField()),
                ('cols', models.ManyToManyField(related_name='column_item', to='hash.Item')),
                ('rows', models.ManyToManyField(related_name='row_item', to='hash.Item')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogo da Velha',
                'verbose_name_plural': 'Jogos da Velha',
            },
        ),
    ]
