# Generated by Django 3.0.2 on 2020-02-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='turn_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
