# Generated by Django 3.0.2 on 2020-02-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0002_hash_turn_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='turn_count',
            field=models.PositiveIntegerField(),
        ),
    ]
