# Generated by Django 3.0.2 on 2020-02-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0004_auto_20200212_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='cols',
            field=models.ManyToManyField(related_name='column_item', to='hash.Item'),
        ),
        migrations.AlterField(
            model_name='hash',
            name='rows',
            field=models.ManyToManyField(related_name='row_item', to='hash.Item'),
        ),
    ]
