# Generated by Django 3.0.2 on 2020-02-12 17:36

from django.db import migrations
import matrix_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0005_auto_20200212_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='matrix',
            field=matrix_field.fields.MatrixField(default=None, max_length=255),
        ),
    ]
