# Generated by Django 3.0.3 on 2020-02-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0006_hash_matrix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hash',
            name='cols',
        ),
        migrations.RemoveField(
            model_name='hash',
            name='rows',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
