# Generated by Django 3.0.3 on 2020-02-20 02:08

from django.db import migrations, models
import matrix_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0007_auto_20200217_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='matrix',
            field=matrix_field.fields.MatrixField(default=[[-1, -1, -1], [-1, -1, -1], [-1, -1, -1]], max_length=255),
        ),
        migrations.AlterField(
            model_name='hash',
            name='turn_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
