# Generated by Django 3.0.3 on 2020-03-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0009_hash_turn_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='is_draw',
            field=models.BooleanField(null=True),
        ),
    ]
