# Generated by Django 3.0.2 on 2020-02-12 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('creation', '0002_auto_20200212_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='game',
        ),
        migrations.AddField(
            model_name='room',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='room',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
