# Generated by Django 3.0.3 on 2020-02-20 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('creation', '0004_auto_20200212_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'hash'), ('model', 'hash')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
