# Generated by Django 3.0.3 on 2020-03-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0005_auto_20200220_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='object_id',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='content_type',
            new_name='game_type',
        ),
    ]
