# Generated by Django 3.0.3 on 2020-03-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0006_auto_20200306_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player_one_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player_two_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
