# Generated by Django 3.0.3 on 2020-03-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0007_auto_20200307_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='owner_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
