# Generated by Django 3.0.3 on 2020-03-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0009_auto_20200307_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='turn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
